apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  name: pg-cluster
  namespace: percona
spec:
  crVersion: 2.8.0
  postgresVersion: 16
  image: percona/percona-distribution-postgresql:16.10-1
  imagePullPolicy: IfNotPresent

  instances:
  - name: instance1
    replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

  proxy:
    pgBouncer:
      image: percona/percona-pgbouncer:1.24.1-1
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  backups:
    pgbackrest:
      image: percona/percona-pgbackrest:2.56.0-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
